### ISSUE TITLE
Support to add prefix and extra header to address field

### ISSUE THREAD

**Issue by DhananjayPurohit** [lightninglabs/aperture#157]
There should be a parameter to include a prefix in the address field. Currently, adding a complete URL to the address results in a `502 Bad Gateway` error. Additionally, a feature to include extra headers in the configuration should be supported.

The service configuration file (`aperture.yaml`) should look like this:
```
- name: "service1"
  hostregexp: "^localhost:8081$"
  pathregexp: '^/api$'
  address: "0.0.0.0:443"
  protocol: https
  header:
    Authorization: "Bearer key"
  price: 10
  rewrite:
    prefix: "/path/to/api"
```
